on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
        paths: [ "src/**" ]

jobs:
    publish:
        runs-on: apexstudios
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true

            - name: Determine version
              id: version
              uses: paulhatch/semantic-version@v5.4.0
              with:
                  change_path: "./"
                  version_format: "${major}.${minor}.${patch}"
                  search_commit_body: true
                  bump_each_commit: true

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  cache-disabled: true # we use a local runner, caching is not required

            - name: Mark Gradle as Executable
              run: chmod +x ./gradlew

            - name: Publish
              run: ./gradlew :publish
              env:
                  VERSION: ${{ steps.version.outputs.version }}
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}