name: Test PR

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: generate-vars
    if: success()
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master
        with:
          java-version: 21
          java-vendor: temurin

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master

      - name: Build with Gradle
        run: ./gradlew :build
        env:
          VERSION: ${{ needs.generate-vars.outputs.version }}

#  publish-maven:
#    name: Publish Maven
#    needs: [ generate-vars, build ]
#    if: success()
#    uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
#    secrets: inherit
#    with:
#      java-version: 21
#      java-vendor: temurin
#      version: ${{ needs.generate-vars.outputs.version }}
#      publish-task: ':publishAllPublicationsToApexStudios-PrivateRepository'
